### ISSUE TITLE
Window filter for emotion of a person over time

### ISSUE THREAD

**Issue by calebescobedo** [Sayter99/face_recognition_ultra_light#13]
Create a window filter for a persons emotion that have a variable t that that is how far back we check in time to average

**Comment by calebescobedo** [comment]
Only change the emotion detection file for  this issue

**Comment by calebescobedo** [comment]
I implemented a VERY simple filter to take the mode of the last x number of emotions detected. Is this too simple for our algorithm? If so, could you please point me in the direction of an algorithm that would give a better value?

**Comment by Sayter99** [comment]
This method looks good to me. I thought it would be better to involve all emotions at first. So, you can maintain a filtered output like `{angry: 55, happy: 20, ...}`. To retrieve all emotions, you can take a look at the program `faces/emotion.py`.

**Comment by calebescobedo** [comment]
Okay, I'm gonna make two different lists for this part. 
1. Total of all emotions seem 
2. Running average of all emotions

**Comment by Sayter99** [comment]
Sounds good, it will give us more flexibility.
