### ISSUE TITLE
Migrate from tensorflow 1 to tensorflow 2 

### ISSUE THREAD

**Issue by calebescobedo** [Sayter99/face_recognition_ultra_light#14]

**Comment by calebescobedo** [comment]
Both files emotion and face detection need to be changed

**Comment by calebescobedo** [comment]
Most of the warning seems to be coming from the libs that both face_detection.py and emotion_detection.py use from keras. Do I need to worry about changing those sections of the code? 

Do you have any advice about how I would go about changing that?

**Comment by Sayter99** [comment]
> Most of the warning seems to be coming from the libs that both face_detection.py and emotion_detection.py use from keras. Do I need to worry about changing those sections of the code?
Tensorflow?

At my end, I received warning messages such as `The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.` So, I think to fix deprecated tf APIs is enough.
